### ISSUE TITLE
JWT clarification

### ISSUE THREAD

**Issue by cobyrne09** [ruddell/generator-jhipster-react-native#260]
Is there a special command/configuration to launch a project with JWT? I see some mention that this package is default JWT compatible, but having launched from `jhipster-sample-app-react-native`, it doesn't quite seem setup for JWT.  This is an awesome package though, so thank you!

**Comment by ruddell** [comment]
Can you describe the issue a little bit more?  Any possible steps to reproduce would help.

The E2E tests all use JWT auth by default and were passing so I'm unsure what the issue is.

During generation, you either pass it the path to your `.yo-rc.json` or JDL file, which should say your authenticationType.  On Web you will need to enable CORS in your backend (see the readme), but other than that you should be able to log in.

**Comment by cobyrne09** [comment]
Apologies for the short explanation. You're right, I was launching with the default JWT configuration, but I was thrown off by what my python API was returning (it was setup to return pseudo-oauth2-with-JWT tokens, but no idToken) via the django-rest-simplejwt package.

That said, I can't quite figure out how to pass in the `.yo-rc.json` to `rnhipster` in the cli... How do you go about this?

It seems like just returning a single JWT might be the easiest, seeing that id have have to change some of the stuff setup for Okta and Keycloak

**Comment by ruddell** [comment]
With JHipster, you can choose either JWT or OAuth2.  In the React Native client, OAuth2 will use a token instead of a cookie (compared to the Angular/React/Vue clients).

Do you have an existing JHipster backend?  That's where you would find your `.yo-rc.json`.  Then to pass it to `rnhipster`, just run `rnhipster` and enter the path to your backend directory.

**Comment by ruddell** [comment]
Closing due to lack of feedback
